# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchPlaces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchPlaces

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'

  target 'SearchPlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchPlacesUITests' do
    # Pods for testing
  end

end
